Add support for max connections
criteo/haproxy-spoe-go pull request #15
Opened 2021-01-05 21:50 UTC by rikatz

Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

Go netutils add support for max connection.

If you surpass this limit, it will be queued by Go until the connection can be processed OR gets a timeout

2021-01-15 17:14 UTC, cpaillet commented
Ok for me, can you just rebase libs ?

2021-01-15 17:36 UTC, rikatz commented
Sure :) Doing right now

2021-01-15 17:45 UTC, rikatz commented
@cpaillet sorry, gofmt changed some other stuff, can revert here if you prefer (only tabs, etc

2021-01-18 08:34 UTC, cpaillet commented
> 
> 
> @cpaillet sorry, gofmt changed some other stuff, can revert here if you prefer (only tabs, etc

Hi,

sorry, my fault. I merge another review to fix that. ( And I just add a linter in the tests )
Next time you can split your PR in 2 review, it's more readable.

2021-01-18 08:35 UTC, cpaillet approved these changes

2021-01-18 15:29 UTC, ShimmerGlass requested changes
Looks good to met. Left a little style suggestion to simplify things.

2021-01-18 15:29 UTC, ShimmerGlass commented on spoe.go
> +		return a.Serve(netutil.LimitListener(lis, a.cfg.MaxConnections))
```suggestion
		lis = netutil.LimitListener(lis, a.cfg.MaxConnections)
```

2021-01-20 14:30 UTC, rikatz commented
@ShimmerGlass thanks, commited your proposal :)

2021-01-21 15:02 UTC, ShimmerGlass commented
Thank you for your contribution!

2021-01-21 15:02 UTC, merged